### ISSUE TITLE
Update Initial Design.md to reflect changes to the original design in the last 2 weeks

### ISSUE THREAD

**Issue by Benallegue-Mehdi** [Phantom65536/csc207-ThoughtVault#13]
Since the original design changed significantly in the last 2 weeks, we should modify the Initial Design.md file accordingly:

- Add Notes class
- Update the classes' structure
- Update view models and views
- Separate input boundaries/interactors as they are now responsible for a single use case
- Add/remove methods if necessary

**Comment by Phantom65536** [comment]
See the initial design.md file in the branch elsie.
